DOWNGRADED to .net6 from >NET8 Because getting below error System.InvalidOperationException   HResult=0x80131509   Message=Error constructing handler for request of type MediatR.IRequestHandler`2[MyWarehouse.Application.Property.GetProperty.GetPropertyListQuery,MyWarehouse.Application.Common.Dependencies.DataAccess.Repositories.Common.IListResponseModel`1[MyWarehouse.Application.Property.GetProperty.GetPropertyDto]]. Register your handlers with the container. See the samples in GitHub for examples.   Source=MediatR   StackTrace:    at MediatR.Wrappers.HandlerBase.GetHandler[THandler](ServiceFactory factory)    at MediatR.Wrappers.RequestHandlerWrapperImpl`2.<>c__DisplayClass1_0.<Handle>g__Handler|0()    at MyWarehouse.Application.Common.Behaviors.RequestValidationBehavior`2.<Handle>d__2.MoveNext() in C:\Users\nevil\OneDrive\Desktop\Projects to learn\workspace\PropertyMasterV4.0\classfiles\Application\Common\Behaviors\RequestValidationBehavior.cs:line 36    at MyWarehouse.Application.Common.Behaviors.ExceptionLoggingBehavior`2.<Handle>d__2.MoveNext() in C:\Users\nevil\OneDrive\Desktop\Projects to learn\workspace\PropertyMasterV4.0\classfiles\Application\Common\Behaviors\ExceptionLoggingBehavior.cs:line 18    at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2.MoveNext()    at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2.MoveNext()    at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2.MoveNext()    at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2.MoveNext()    at MediatR.Pipeline.RequestPostProcessorBehavior`2.<Handle>d__2.MoveNext()    at MediatR.Pipeline.RequestPreProcessorBehavior`2.<Handle>d__2.MoveNext()    at MyWarehouse.Infrastructure.API.V1.PropertyController.<GetList>d__2.MoveNext() in C:\Users\nevil\OneDrive\Desktop\Projects to learn\workspace\PropertyMasterV4.0\WebApi\API\V1\PropertyController.cs:line 27
  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ArgumentException: GenericArguments[0], 'System.Int32', on 'T MaxFloat[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.

Inner Exception 2:
VerificationException: Method System.Linq.Enumerable.MaxFloat: type argument 'System.Int32' violates the constraint of type parameter 'T'.